## Ejercicios clase 1 

In [17]:
import numpy as np

### Ejercicio 1 

In [21]:
def vector_norm_l0(matrix):
    mask = matrix > 0
    return np.sum(mask, axis=1)

def vector_norm_lx(matrix, p):
    return np.sum(np.abs(matrix)**p, axis=1)**(1/p)

def vector_norm_inf(m):
    return np.max(m, axis=1)

# Matriz random
X = np.random.random((3,3))

print("Matriz random: ")
print(X)
print("Norma l0:")
print("         ",vector_norm_l0(X))
print("Norma l1:")
print("         ",vector_norm_lx(X, 1))
print("Norma l2:")
print("         ",vector_norm_lx(X, 2))
print("Norma infinito:")
print("         ",vector_norm_inf(X))

Matriz random: 
[[0.79842065 0.1614764  0.15391292]
 [0.22604947 0.24110864 0.93581906]
 [0.97561966 0.14881256 0.98608671]]
Norma l0:
          [3 3 3]
Norma l1:
          [1.11380997 1.40297717 2.11051893]
Norma l2:
          [0.82899901 0.99246615 1.39511501]
Norma infinito:
          [0.79842065 0.93581906 0.98608671]


### Ejercicio 2 

In [22]:
x = np.random.random((3,3))
print("X: " + str(x))

p_norms = vector_norm_lx(X, 2)
indexes = np.argsort(p_norms * -1)

print("Indexes: " + str(indexes))
print(x[indexes])

X: [[0.39869553 0.90601511 0.26361902]
 [0.4197178  0.89817675 0.18871703]
 [0.11188725 0.71729296 0.55719546]]
Indexes: [2 1 0]
[[0.11188725 0.71729296 0.55719546]
 [0.4197178  0.89817675 0.18871703]
 [0.39869553 0.90601511 0.26361902]]


### Ejercicio 3

In [24]:
class index(object):
    def __init__(self, usr_id):
        unique_id = np.unique(usr_id)
        id2idx = np.ones(unique_id.max() + 1, dtype=np.int64) * -1
        id2idx[unique_id] = np.arange(unique_id.size)
        self.id2idx = id2idx
        self.idx2id = unique_id
    
    def get_user_idx(self, ids):
        ids = self.id2idx[ids]
        return ids
    
    def get_user_id(self, idxs):
        return self.idx2id[idxs]

idxManager = index([15, 12, 14, 10, 1, 2, 1])

print("Indice del usuario 15: ",idxManager.get_user_idx(15))
print("Indice del usuario 10: ",idxManager.get_user_idx(10))
print("Indice del usuario 6 (no existente): ",idxManager.get_user_idx(6))

print("Usuario del indice 0: ",idxManager.get_user_id(0))
print("Usuario del indice 4: ",idxManager.get_user_id(4))

Indice del usuario 15:  5
Indice del usuario 10:  2
Indice del usuario 6 (no existente):  -1
Usuario del indice 0:  1
Usuario del indice 4:  14


### Ejercicio 4

In [26]:
truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

#Bitwise operations
TP = np.sum((truth == True) & (prediction == True))
TN = np.sum((truth == False) & (prediction == False))
FN = np.sum((truth == True) & (prediction == False))
FP = np.sum((truth == False) & (prediction == True))

precision = TP / (TP + FP)
recall = TP / (TP + FN)
accuracy = (TP + TN) / (TP + TN + FP + FN)

print("Precision: " + str(precision))
print("Recall: " + str(recall))
print("Accuracy: " + str(accuracy))

Precision: 0.5
Recall: 0.5
Accuracy: 0.4


### Ejercicio 5

In [30]:
q_Id            = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4])
truth_Relevance = np.array([True, False, True, False, True, True, True, False, False, False, False, False, True, False, False, True])

q_precision = np.zeros((4,1))

for i in range(4):
    q_precision[i] = truth_Relevance[q_Id == (i+1)].mean()
    print("Precision for id " + str(i) + ": " + str(q_precision[i]))

print("Average query precision: " + str(q_precision.mean()))

Precision for id 0: [0.5]
Precision for id 1: [1.]
Precision for id 2: [0.]
Precision for id 3: [0.5]
Average query precision: 0.5


### Ejercicio 6

In [43]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
C = np.array([[1,0,0],[0,1,1]])

C_exp = C[:, np.newaxis]

diff = C_exp - X

distance = vector_norm_lx(diff, 2)

print(diff)
print(distance)


[[[ 0 -2 -3]
  [-3 -5 -6]
  [-6 -8 -9]]

 [[-1 -1 -2]
  [-4 -4 -5]
  [-7 -7 -8]]]
[[ 6.70820393  9.64365076 11.22497216]
 [ 8.1240384   8.1240384   9.64365076]]


### Ejercicio 7

In [44]:
min_distance = np.argmin(distance, axis=0)

print(min_distance)

[0 1 1]


### Ejercicio 10

In [ ]:
# dataset link: https://www.kaggle.com/rounakbanik/the-movies-dataset/data?select=ratings.csv
import pickle
import csv

class MovieRatings:
    
    instance = None
    data = None
    
    def __new__(cls, fname):
        if MovieRatings.instance is None:
            print("Creating new MovieRatings instance")
            MovieRatings.instance = super(MovieRatings, cls).__new__(cls)
            return MovieRatings.instance
        else:
            return MovieRatings.instance
        
    def __init__(self, fname):
        print("Initialising MovieRatings")
        
        try:
            with open(fname + '.pkl','rb') as pkl_file:
                self.data = pickle.load(pkl_file)
        except FileNotFoundError:
            print("CSV file found. Building PKL file...")
            try:
                with open(fname + '.csv') as csv_file:
                    with open(fname + '.pkl','wb') as pkl_file:
                        
                        csv_reader = csv.reader(csv_file, delimiter=',')

                        def generator(csv_reader):
                            first_skipped = False
                            for line in csv_reader:
                                if not first_skipped:
                                    first_skipped = True
                                    continue
                                yield(line[0],line[1],line[2],line[3])
                        
                        gen = generator(csv_reader)     
                        
                        structure = [('userId', np.int32),
                                    ('movieId', np.int32),
                                    ('rating', np.float32),
                                    ('timestamp', np.int64)]
                        
                        array = np.fromiter(gen, dtype=structure)
                        
                        pickle.dump(array, pkl_file, protocol=pickle.HIGHEST_PROTOCOL)
                        
                    pkl_file.close()
                
                with open(fname + '.pkl','rb') as pkl_file:
                    self.data = pickle.load(pkl_file)
            except FileNotFoundError:
                print("No PKL or CSV named " + fname + " was found.")
            finally:
                csv_file.close()
        finally:
            pkl_file.close()

obj = MovieRatings('ratings')
print(obj.data[1])
obj2 = MovieRatings('ratings')